apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blocky.rules
  namespace: networking
spec:
  groups:
  - name: blocky.rules
    rules:
    - alert: BlockyAbsent
      annotations:
        description: "DNS ad blocking will be down until Blocky is back up"
        summary: "Blocky has disappeared from Prometheus service discovery."
      expr: |
        absent(up{job="blocky"})
      for: 5m
      labels:
        severity: critical
