---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: minio-operator
  name: minio.rules
  namespace: minio
spec:
  groups:
    - name: minio.rules
      rules:
        - alert: MinioAbsent
          expr: |
            absent(up{job=~".*minio.*"} == 1)
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: MinIO component has disappeared.
            description: MinIO has dissapeared from Prometheus service discovery.
        - alert: MinioDiskOffline
          expr: |
            minio_cluster_disk_offline_total != 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: MinIO disk offline.
            description: MinIO is reporting {{ $value }} disk(s) offline
              on server {{ $labels.server }}
        - alert: MinioNodeOffline
          expr: |
            minio_cluster_nodes_offline_total != 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: MinIO node is offline.
            description: MinIO is reporting that node {{ $labels.server }} is offline.
        - alert: MinioClusterUsage
          expr: |
            sum(minio_cluster_capacity_usable_free_bytes)
              /
            sum(minio_cluster_capacity_usable_total_bytes)
              < .10
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: MinIO cluster is low on capacity.
            description: MinIO cluster is reporting less than 10% storage free.
              {{ $value | humanizePercentage }} of cluster storage is available.
        - alert: MinioNodeDiskUsage
          expr: |
            sum(minio_node_disk_free_bytes) by (server)
              /
            sum(minio_node_disk_total_bytes) by (server)
              < .10
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: MinIO node is low on disk space.
            description: MinIO node is reporting less than 10% disk space available.
              {{ $value | humanizePercentage }} of disk space available on node {{ $labels.server }}
