apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: speedtest-exporter
  name: speedtest-exporter.rules
  namespace: monitoring
spec:
  groups:
  - name: speedtest-exporter.rules
    rules:
    - alert: SpeedtestExporterDown
      annotations:
        message: "Speedtest Exporter has disappeared from Prometheus target discovery."
      expr: |
        absent(up{job="speedtest-exporter"})
      for: 5m
      labels:
        severity: critical
    - alert: SpeedtestSlowInternetDownload
      expr: |
        avg_over_time(speedtest_download[6h])
          < 420
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "SpeedTest Slow Internet Download (instance {{ $labels.instance }})"
        description: "Internet download speed is currently {{ humanize $value }} Mbps.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: SpeedtestSlowInternetUpload
      expr: |
        avg_over_time(speedtest_upload[6h])
          < 420
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "SpeedTest Slow Internet Upload (instance {{ $labels.instance }})"
        description: "Internet upload speed is currently {{ humanize $value }} Mbps.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
