---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nut-exporter
spec:
  groups:
    - name: nut-exporter
      rules:
        - alert: NutExporterDown
          annotations:
            description: NUT Exporter has disappeared from Prometheus target discovery.
            summary: NUT Exporter is down.
          expr: |
            absent(up{job="nut-exporter"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: UpsStatusUnknown
          annotations:
            description: UPS {{ $labels.ups }} is reporting a status of unknown.
            summary: UPS status unknown.
          expr: |
            nut_status{job="nut-exporter"} == 0
          for: 10s
          labels:
            severity: critical
        - alert: UpsOnBattery
          annotations:
            description: UPS {{ $labels.ups }} has lost power and is running on battery.
            summary: UPS is running on battery.
          expr: |
            nut_status{job="nut-exporter"} == 2
          for: 10s
          labels:
            severity: critical
        - alert: UpsLowBattery
          annotations:
            description: UPS {{ $labels.ups }} battery is low and the system is getting
              ready to shutdown.
            summary: UPS battery is low.
          expr: |
            nut_status{job="nut-exporter"} == 3
          for: 5s
          labels:
            severity: critical
