---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gluster.rules
spec:
  groups:
    - name: gluster.rules
      rules:
        - expr: |
            sum by (job) (max(gluster_subvol_capacity_used_bytes{job="glusterd2-client"}) by (job, volume, subvolume))
          record: gluster:volume_capacity_used_bytes_total:sum
        - expr: |
            sum by (job) (max(gluster_subvol_capacity_total_bytes{job="glusterd2-client"}) by (job, volume, subvolume))
          record: gluster:volume_capacity_total_bytes:sum
