---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: thanos-receive.rules
spec:
  groups:
    - name: thanos-receive.rules
      rules:
        - expr: |
            (
              sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", job=~".*thanos-receive.*", grpc_type="unary"}[5m]))
            /
              sum by (job) (rate(grpc_server_started_total{job=~".*thanos-receive.*", grpc_type="unary"}[5m]))
            )
          record: :grpc_server_failures_per_unary:sum_rate
        - expr: |
            (
              sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", job=~".*thanos-receive.*", grpc_type="server_stream"}[5m]))
            /
              sum by (job) (rate(grpc_server_started_total{job=~".*thanos-receive.*", grpc_type="server_stream"}[5m]))
            )
          record: :grpc_server_failures_per_stream:sum_rate
        - expr: |
            (
              sum by (job) (rate(http_requests_total{handler="receive", job=~".*thanos-receive.*", code!~"5.."}[5m]))
            /
              sum by (job) (rate(http_requests_total{handler="receive", job=~".*thanos-receive.*"}[5m]))
            )
          record: :http_failure_per_request:sum_rate
        - expr: |
            histogram_quantile(0.99,
              sum by (job, le) (rate(http_request_duration_seconds_bucket{handler="receive", job=~".*thanos-receive.*"}[5m]))
            )
          labels:
            quantile: "0.99"
          record: :http_request_duration_seconds:histogram_quantile
        - expr: |
            (
              sum by (job) (rate(thanos_receive_replications_total{result="error", job=~".*thanos-receive.*"}[5m]))
            /
              sum by (job) (rate(thanos_receive_replications_total{job=~".*thanos-receive.*"}[5m]))
            )
          record: :thanos_receive_replication_failure_per_requests:sum_rate
        - expr: |
            (
              sum by (job) (rate(thanos_receive_forward_requests_total{result="error", job=~".*thanos-receive.*"}[5m]))
            /
              sum by (job) (rate(thanos_receive_forward_requests_total{job=~".*thanos-receive.*"}[5m]))
            )
          record: :thanos_receive_forward_failure_per_requests:sum_rate
        - expr: |
            (
              sum by (job) (rate(thanos_receive_hashrings_file_errors_total{job=~".*thanos-receive.*"}[5m]))
            /
              sum by (job) (rate(thanos_receive_hashrings_file_refreshes_total{job=~".*thanos-receive.*"}[5m]))
            )
          record: :thanos_receive_hashring_file_failure_per_refresh:sum_rate
