---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: speedtest-exporter
spec:
  groups:
    - name: speedtest-exporter
      rules:
        - alert: SpeedtestExporterAbsent
          annotations:
            description: Speedtest Exporter has disappeared from Prometheus target discovery.
            summary: Speedtest Exporter is down.
          expr: |
            absent(up{job=~".*speedtest.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: SpeedtestSlowInternetDownload
          annotations:
            description: Internet download speed is averaging {{ humanize $value }} Mbps.
            summary: SpeedTest slow internet download.
          expr: |
            avg_over_time(speedtest_download[4h])
              < 420
          for: 0m
          labels:
            severity: warning
        - alert: SpeedtestSlowInternetUpload
          annotations:
            description: Internet upload speed is averaging {{ humanize $value }} Mbps.
            summary: SpeedTest slow internet upload.
          expr: |
            avg_over_time(speedtest_upload[4h])
              < 420
          for: 0m
          labels:
            severity: warning
