---
name: Verify Prometheus Rules with Promtool

on:
  push:
    branches:
      - main
    paths:
      - "**.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "**.yaml"

jobs:
  verify_rules:
    name: On Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Verify Prometheus rules
        uses: peimanja/promtool-github-actions@master
        with:
          promtool_actions_subcommand: 'rules'
          promtool_actions_files: '**.yaml'
          promtool_actions_version: '2.14.0'
          promtool_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
